In [1]:
import pandas as pd
from bs4 import BeautifulSoup

In [25]:
#attempt at reading a csv file connected with former idea related to trans 
pd.read_csv('../data/project.ideas/trans.covid/2021_06JUN_04_TransNB_CovidDisparitiesGroup.original.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 16: invalid start byte

In [26]:
#attempt after saving with encoding utf-8
pd.read_csv('../data/project.ideas/trans.covid/2021_06JUN_04_TransNB_CovidDisparitiesGroup.utf8.csv')

      504b 0304 1400 0600 0800 0000 2100 7c6c
0     9816 6901 0000 a005 0000 1300 0802 5b43
1     6f6e 7465 6e74 5f54 7970 6573 5d2e 786d
2     6c20 a204 0228 a000 0200 0000 0000 0000
3     0000 0000 0000 0000 0000 0000 0000 0000
4     0000 0000 0000 0000 0000 0000 0000 0000
...                                       ...
7569  0006 0008 0000 0021 0020 080f 729b 0100
7570  0047 0300 0010 0000 0000 0000 0000 0000
7571  0000 0029 d301 0064 6f63 5072 6f70 732f
7572  6170 702e 786d 6c50 4b05 0600 0000 000d
7573         000d 005d 0300 00fa d501 0000 00

[7574 rows x 1 columns]

In [27]:
#initial load of duolingo learner interaction
pd.read_csv('../data/project.ideas/duolingo/settles.acl16.learning_traces.13m.csv')

,p_recall,timestamp,delta,user_id,learning_language,ui_language,lexeme_id,lexeme_string,history_seen,history_correct,session_seen,session_correct
0,1.000000,1362076081,27649635,u:FO,de,en,76390c1350a8dac31186187e2fe1e178,lernt/lernen<vblex><pri><p3><sg>,6,4,2,2
1,0.500000,1362076081,27649635,u:FO,de,en,7dfd7086f3671685e2cf1c1da72796d7,die/die<det><def><f><sg><nom>,4,4,2,1
2,1.000000,1362076081,27649635,u:FO,de,en,35a54c25a2cda8127343f6a82e6f6b7d,mann/mann<n><m><sg><nom>,5,4,1,1
3,0.500000,1362076081,27649635,u:FO,de,en,0cf63ffe3dda158bc3dbd55682b355ae,frau/frau<n><f><sg><nom>,6,5,2,1
4,1.000000,1362076081,27649635,u:FO,de,en,84920990d78044db53c1b012f5bf9ab5,das/das<det><def><nt><sg><nom>,4,4,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
12854221,0.800000,1363104897,368,u:i5D8,en,it,d5efc552aaea3109eb5388aa1ec8673d,the/the<det><def><sp>,6,4,5,4
12854222,0.800000,1363104897,368,u:i5D8,en,it,a826c47947d68549fa81e19cafa57ba0,eat/eat<vblex><pres>,4,4,5,4
12854223,1.000000,1363104897,368,u:i5D8,en,it,5e29d77697d23070a1fb92eb6c90e9b6,bread/bread<n><sg>,4,4,4,4
12854224,0.600000,1363104897,368,u:i5D8,en,it,cdfecc9247566d40bb964a218c54c783,drink/drink<vblex><pres>,3,2,5,3
12854225,0.666667,1363104897,368,u:i5D8,en,it,c52ab45d4e22ee7580041911159e3c0c,water/water<n><sg>,5,3,9,6

In [31]:
# initial load of sonoma county trans homelessness census data
pd.read_csv('../data/project.ideas/homelessness/query-8034011b3f8adbd765ee7dead7bb151d3e257a64-20220918-230456.csv')

,:id,transgender_total,census_tract,year,:@computed_region_xw9s_pz78,location_1_city,male_total,female_total,location_1,location_1_state,:@computed_region_dig5_f3vy,location_1_address,location_1_zip
0,row-mvry_3sbh~yvfs,0,150304,2018,5.0,NaN,10,4,"{""latitude"": ""38.306744944629"", ""longitude"": ""...",NaN,31040,NaN,NaN
1,row-fi9p-6axp~axuy,0,150305,2018,6.0,NaN,4,0,"{""latitude"": ""38.325896866331"", ""longitude"": ""...",NaN,31040,NaN,NaN
2,row-ipuq_ties_j7zu,0,151000,2018,18.0,NaN,2,1,"{""latitude"": ""38.257657374591"", ""longitude"": ""...",NaN,11138,NaN,NaN
3,row-amvh.827p~5d33,0,151307,2018,31.0,NaN,15,5,"{""latitude"": ""38.370514067193"", ""longitude"": ""...",NaN,1829,NaN,NaN
4,row-wz3z_rvc9_jxbe,0,151308,2018,32.0,NaN,10,2,"{""latitude"": ""38.356290146564"", ""longitude"": ""...",NaN,1829,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,row-dg2b_v7cp-snw3,0,150901,2017,23.0,NaN,32,9,"{""latitude"": ""38.244613607937"", ""longitude"": ""...",NaN,11138,NaN,NaN
96,row-mnyq_dy94.qcn5,0,153001,2018,64.0,NaN,27,53,"{""latitude"": ""38.450938862368"", ""longitude"": ""...",NaN,26075,NaN,NaN
97,row-w27i.wg79-s8jx,0,152501,2017,52.0,NaN,8,0,"{""latitude"": ""38.465578375752"", ""longitude"": ""...",NaN,26080,NaN,NaN
98,row-8zez.x2js~ncpq,0,153804,2017,88.0,NaN,1,0,"{""latitude"": ""38.556537202286"", ""longitude"": ""...",NaN,31428,NaN,NaN
99,row-5vta.d5tg~2jni,0,152802,2017,59.0,NaN,0,2,"{""latitude"": ""38.465144532659"", ""longitude"": ""...",NaN,26076,NaN,NaN